import { Inter } from "next/font/google";
import "./globals.css";
// import { firebaseConfig } from "@/firebase";
// import { Firestore } from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MealHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/assets/favicon32.png"></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
